[package]
name = "is_not_decreasing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display = "0.1.2"
fmt = "0.1.0"
